package com.Student_Library_Management.Models;

import ch.qos.logback.core.boolex.EvaluationException;
import com.Student_Library_Management.ENUMS.Genre;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "Book")
@Getter
@Setter
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // use for autoGenerated id's
    private int id;

    private String bookName;
    private int pages;

    @Enumerated(value=EnumType.STRING) //For Creating Genre we've created it's ENUMS
    private Genre genre;

    private boolean issued;

//    mapping : author is to book
    //[We're setting Foreign key here] book is child with respective to author -
    @ManyToOne
    @JoinColumn
    private Author author;

//  mapping : card is to book [book is also child with Respect to card class]
    @ManyToOne //  many books one card
    @JoinColumn
    private Card card;


    public Book(){}
}
